ssbostan/terraform-awesome

examples/docker/moderate-pull-new-image-layers-container/main.tf, examples/docker/moderate-pull-new-image-layers-container/providers.tf, examples/docker/moderate-pull-new-image-layers-container/terraform.tf
hi! i added 05 example:docker moderate-pull-new-image-layers-container
=> add example:docker moderate-pull-new-image-layers-container

examples/docker/easy-build-image-build-args/Dockerfile, examples/docker/easy-build-image-build-args/main.tf, examples/docker/easy-build-image-build-args/providers.tf, examples/docker/easy-build-image-build-args/terraform.tf, examples/docker/easy-install-docker-plugin/main.tf, examples/docker/easy-install-docker-plugin/providers.tf, examples/docker/easy-install-docker-plugin/terraform.tf
This pull request is for task no 3 : easy-build-image-build-args
=> add example:docker easy-build-image-build-args

examples/docker/easy-mysql-simple-container/main.tf, examples/docker/easy-mysql-simple-container/providers.tf, examples/docker/easy-mysql-simple-container/terraform.tf
add example:docker easy-mysql-simple-container
=> add example:docker easy-mysql-simple-container

README.md, examples/docker/easy-nginx-with-root-dir/main.tf, examples/docker/easy-nginx-with-root-dir/nginx.conf, examples/docker/easy-nginx-with-root-dir/providers.tf, examples/docker/easy-nginx-with-root-dir/terraform.tf
32 create nginx container with all needed options, publish port and mount nginx root dir easy-nginx-with-root-dir
=> add example:docker easy-nginx-with-root-dir

examples/docker/moderate-import-existing-container/import.sh, examples/docker/moderate-import-existing-container/main.tf, examples/docker/moderate-import-existing-container/providers.tf, examples/docker/moderate-import-existing-container/terraform.tf, examples/docker/moderate-import-existing-network/import.sh, examples/docker/moderate-import-existing-network/main.tf, examples/docker/moderate-import-existing-network/providers.tf, examples/docker/moderate-import-existing-network/terraform.tf
This pull request related to task 23 import an existing container to terraform `moderate-import-existing-container`  and 13 import an existing network to terraform `moderate-import-existing-network`
=> add example:docker moderate-import-existing-container

examples/docker/moderate-volume-nfs-storage/main.tf, examples/docker/moderate-volume-nfs-storage/providers.tf, examples/docker/moderate-volume-nfs-storage/terraform.tf
Task 07: moderate-volume-nfs-storage completed.
=> add example:docker moderate-volume-nfs-storage

examples/tls/easy-sign-csr-certificate/main.tf
=> add example:tls easy-sign-csr-certificate

examples/tls/easy-csr-with-new-private-key/main.tf
05 create a new private key and a new CSR file easy-csr-with-new-private-key
=> add example:tls easy-csr-with-new-private-key

examples/kubernetes/easy-kubernetes-secret-string-data/main.tf, examples/kubernetes/easy-kubernetes-secret-string-data/providers.tf, examples/kubernetes/easy-kubernetes-secret-string-data/terraform.tf
This  pull request related to task 004 create Secret with string data `easy-kubernetes-secret-string-data`
=> add example:kubernetes easy-kubernetes-secret-string-data

examples/kubernetes/easy-kubernetes-pod-container-httpget-startup-probe/main.tf, examples/kubernetes/easy-kubernetes-pod-container-httpget-startup-probe/providers.tf, examples/kubernetes/easy-kubernetes-pod-container-httpget-startup-probe/terraform.tf
=> add example:kubernetes easy-kubernetes-pod-container-httpget-startup-probe

examples/docker/moderate-wordpress-stack-production/main.tf, examples/docker/moderate-wordpress-stack-production/provider.tf, examples/docker/moderate-wordpress-stack-production/terraform.tf, examples/docker/moderate-wordpress-stack-production/wordpress/conf/config-file.conf, examples/docker/moderate-wordpress-stack-production/wordpress/nginx-conf/nginx.conf, examples/docker/moderate-wordpress-stack-production/wordpress/uploads.ini
add example:docker moderate-wordpress-stack-production
=> add example:docker moderate-wordpress-stack-production

examples/tls/easy-dns-ip-subject-certificate/main.tf
add example:tls easy-dns-ip-subject-certificate
=> add example:tls easy-dns-ip-subject-certificate

examples/docker/moderate-import-existing-docker-plugin/import.sh, examples/docker/moderate-import-existing-docker-plugin/main.tf, examples/docker/moderate-import-existing-docker-plugin/providers.tf, examples/docker/moderate-import-existing-docker-plugin/terraform.tf
Task 10:moderate-import-existing-docker-plugin completed.
=> add example:docker moderate-import-existing-docker-plugin

examples/kubernetes/easy-kubernetes-persistent-volume-nfs/main.tf, examples/kubernetes/easy-kubernetes-persistent-volume-nfs/providers.tf, examples/kubernetes/easy-kubernetes-persistent-volume-nfs/terraform.tf
I've completed task 029: Create PersistentVolume for `NFS easy-kubernetes-persistent-volume-nfs`
=> add example:kubernetes easy-kubernetes-persistent-volume-nfs

examples/kubernetes/easy-kubernetes-namespace/main.tf, examples/kubernetes/easy-kubernetes-namespace/providers.tf, examples/kubernetes/easy-kubernetes-namespace/terraform.tf
add example:kubernetes easy-kubernetes-namespace
=> add example:kubernetes easy-kubernetes-namespace

examples/kubernetes/easy-namespace-default-service-account/main.tf, examples/kubernetes/easy-namespace-default-service-account/providers.tf, examples/kubernetes/easy-namespace-default-service-account/terraform.tf
add 010 create default ServiceAccount in specific namespace `easy-namespace-default-service-account`
=> add example:kubernetes easy-namespace-default-service-account

examples/kubernetes/easy-kubernetes-resource-quota/main.tf, examples/kubernetes/easy-kubernetes-resource-quota/providers.tf, examples/kubernetes/easy-kubernetes-resource-quota/terraform.tf
add 012 create ResourceQuota resource `easy-kubernetes-resource-quota`
=> add example:kubernetes easy-kubernetes-resource-quota

examples/kubernetes/easy-kubernetes-pod-container-tcpsocket-readiness-probe/main.tf, examples/kubernetes/easy-kubernetes-pod-container-tcpsocket-readiness-probe/providers.tf, examples/kubernetes/easy-kubernetes-pod-container-tcpsocket-readiness-probe/terraform.tf
Task 091:easy-kubernetes-pod-container-tcpsocket-readiness-probe completed.
=> add example:kubernetes easy-kubernetes-pod-container-tcpsocket-readiness-probe

examples/kubernetes/easy-kubernetes-pod-container-security-context/main.tf, examples/kubernetes/easy-kubernetes-pod-container-security-context/providers.tf, examples/kubernetes/easy-kubernetes-pod-container-security-context/terraform.tf
Task 095:easy-kubernetes-pod-container-security-context completed.
=> add example:kubernetes easy-kubernetes-pod-container-security-context

examples/kubernetes/easy-kubernetes-role/main.tf, examples/kubernetes/easy-kubernetes-role/providers.tf, examples/kubernetes/easy-kubernetes-role/terraform.tf
Task 050:easy-kubernetes-role completed.
=> add example:kubernetes easy-kubernetes-role
